# Use postgres/example user/password credentials
version: '3.1'

services:
  db:
    image: postgres
    restart: always
    build:
      context: .
      dockerfile: db/DockerFile
    environment:
      POSTGRES_DB: apisales
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - './db:/var/lib/postgresql/db'
    ports:
      - 5432:5432

  redis:
    env_file: .env
    restart: always
    image: redis:alpine
    command: >
      --requirepass ${REDIS_PASSWORD}
    ports:
      - '${REDIS_PORT}:6379'
